spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blogdb?useLegacyDatetimeCode=false}
    useJDBCCompliantTimeZoneShift: true
    serverTimezone: Asia/Tokyo
    username: root
    password: testtest
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Tokyo
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: #gmail login
    password:  #somepassword (application password generated for your google account)
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
server:
  port: ${PORT:8080}
captcha:
  delete_timeout: 60 # min
  random_secret_key_length: 22
  image:
    format: png
    format_string: data:image/png;base64
    text:
      length: 5
      font:
        random_font1: SanSerif
        random_font2: Serif
        random_font3: Monospaced
    width: 103
    height: 56
post_comment:
  min_length: 10
  max_length: 10000
post:
  image:
    root_folder: images
    upload_folder: upload
    format: jpg
  body:
    min_length: 100
    max_length: 15000
  title:
    min_length: 5
    max_length: 150
  default_limit_per_page: 10
  announce:
    max_length: 200
user:
  timeout_edit_profile: 3600000 # ms
  password:
    restore_key_length: 45
    restore_pass_message_string: "/login/change-password/"    # + код для восстановления
    restore_message_subject: "Ссылка для восстановление пароля"
    validation_regex: "^.{6,}$"
    hashing_algorithm: MD5
  image:
    root_folder: images
    upload_folder: upload
    avatars_folder: avatars
    format: jpg
    upload_timeout_ms: 3600000
    max_size: 5000000 # bytes
  email:
    validation_regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}"
global_settings:
  default_values:   # items accept values "YES" or "NO"
    multiuser_mode: "YES"
    statistics_is_public: "YES"
    post_premoderation: "YES"
general_data:
  title: "DevPub"
  subtitle: "Рассказы разработчиков"
  phone: "+7 903 666-44-55"
  email: "mail@mail.ru"
  copyright: "Дмитрий Сергеев"
  copyright_from: "2005"