version: "3.7"
services:
  service:
    build: .
    restart: always
    ports:
      - 8082:8080
    networks:
      - blogdb-net
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/blogdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - spring.flyway.url=jdbc:mysql://db:3306/blogdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2

  db:
    image: "mysql:8.0.35"
    restart: always
    networks:
        - blogdb-net
    ports:
      - 3306:3306
    volumes:
    - ~/data/docker/volumes/mysql8:/var/lib/mysql
networks:
  blogdb-net: