version: "3.7"

services:
  service:
    container_name: blog-app
    build: .
    restart: always
    ports:
      - 8082:8080
    networks:
      - blog-net
    volumes:
      - .m2:/root/.m2
      - blog_images:/images

  certbot:
    image: certbot/certbot
    container_name: blog-certbot
    volumes:
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email surkov.r.b@gmail.com --agree-tos --no-eff-email --staging -d blog.surkoff.com -d www.blog.surkoff.com -d keycloak.surkoff.com -d www.keycloak.surkoff.com
    networks:
      - blog-net

networks:
  blog-net:

volumes:
  blog_images:
    driver: local