version: "3.7"

services:
  service:
    container_name: blog-app
    build: .
    restart: always
    ports:
      - 8082:8080
    networks:
      - blog-net
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/blogdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - spring.flyway.url=jdbc:mysql://db:3306/blogdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2
      - ~/data/docker/volumes/blog/images:/images

  db:
    image: "mysql:8.0.35"
    container_name: blog-db
    environment:
      MYSQL_DATABASE: testblogdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - blog-net
    ports:
      - 3306:3306
    volumes:
      - ~/data/docker/volumes/mysql8:/var/lib/mysql

  certbot:
    image: certbot/certbot
    container_name: blog-certbot
    volumes:
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email surkov.r.b@gmail.com --agree-tos --no-eff-email --force-renewal -d blog.surkoff.com -d www.blog.surkoff.com
    networks:
      - blog-net

networks:
  blog-net: