version: "3.7"
services:
  service:
    build: .
    restart: always
    ports:
      - 8082:8080
    networks:
      - blogdb-net
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/blogdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - spring.flyway.url=jdbc:mysql://db:3306/blogdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2

  db:
    image: "mysql:8.0.35"
    environment:
      MYSQL_DATABASE: testblogdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - 3306:3306
    networks:
      - blogdb-net
    volumes:
      - ~/data/docker/volumes/mysql8:/var/lib/mysql

  caddy:
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "reverse-proxy", "--from", "blog.surkoff.com", "--to", "service:8080"]

networks:
  blogdb-net:
volumes:
  caddy_data:
  caddy_config:
